"""added review and check user model-2

Revision ID: 7b4046e579d1
Revises: 6dd61c050bad
Create Date: 2026-01-14 20:23:09.247503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4046e579d1'
down_revision: Union[str, Sequence[str], None] = '6dd61c050bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    # ### end Alembic commands ###
