"""added review and check user model

Revision ID: 6dd61c050bad
Revises: 09868ba2a8be
Create Date: 2026-01-14 20:19:31.277107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd61c050bad'
down_revision: Union[str, Sequence[str], None] = '09868ba2a8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('review', sa.String(length=255), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reviews_id'), 'user_reviews', ['id'], unique=False)
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'github')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'location')
    op.drop_index(op.f('ix_user_reviews_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    # ### end Alembic commands ###
