"""added admin activity models-2

Revision ID: 76bb3b3c30a0
Revises: 6ea62bf778f8
Create Date: 2026-01-15 12:40:35.725337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bb3b3c30a0'
down_revision: Union[str, Sequence[str], None] = '6ea62bf778f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
